### ISSUE TITLE
Add rollout for feature flipping

### ISSUE THREAD

**Issue by quamen** [aerobicio/aerobic.io#25]
[Rollout](https://github.com/bitlove/rollout) is a gem that provides the ability to feature flip. It's backed by Redis.

This is quite a big change, it involves changes to all of our existing infrastructure and documentation.
## Todo
- [x] Add Redis to the application.
- [x] Add Redis to Wercker.
- [x] Add Redis to Heroku.
- [x] Add [Rollout](https://github.com/bitlove/rollout) to the application.
- [x] Prove that it all works somehow.
- [x] Update README with information on how it works.
