### ISSUE TITLE
Activity Feed

### ISSUE THREAD

**Issue by plasticine** [aerobicio/aerobic.io#42]
> On the dashboard for now. This is where you see your activity, activity of members you follow and activity of members who belong to a group you have joined.

This issue is not about groups or following. This is about showing all activity of all members in one place. 

Scoping by following and groups will come later.

---

```
Given I am a member
When I add a workout
Then I should see it in my activity feed
```

```
Given I am a member
When another member adds a workout
Then I should see it in my activity feed
```

---
## Todo
- [x] Add WIP features for the activity feed
- [x] Add domain model for workout
- [x] Add ability to instantiate workout domain models from AR objects
- [x] Add ability to write workout domain models to json
- [x] Add ability to instantiate workout domain models from json
- [x] Have workout domain model write to AR and Redis on create/update
- [x] Have workout domain model write to activity feeds on create
- [x] Replace dashboard with redis powered activity feed
- [x] ~~Re-write upload_from_garmin.feature to look for workout/show page instead of activity feed~~
- [x] Move non AR models objects out of app/models
- [x] Update README
